version: "3.9"

services:
  db:
    image: mysql:8
    container_name: hostel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: hostel_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin@123
      DB_NAME: hostel_db
      DB_PORT: 3306

volumes:
  db_data:
