#version: "3.9"

services:
  db:
    image: mariadb:10.6
    container_name: hostel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: hostel_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: hostel-web
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_HOST: db        # Use service name for internal network
      DB_PORT: 3306
      DB_NAME: hostel_db
      DB_USER: root
      DB_PASSWORD: admin@123
    volumes:
      - .:/app

volumes:
  db_data:
