services:
  db:
    image: mariadb:10.6
    container_name: hostel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: hostel_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: hostel-web
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: hostel_db
      DB_USER: root
      DB_PASSWORD: admin@123
    command: gunicorn --bind 0.0.0.0:5000 app:app --access-logfile - --error-logfile -
    logging:
      driver: splunk
      options:
        splunk-url: "http://3.109.223.23:8088"   # or http://... if SSL disabled
        splunk-token: "58ddf65e-e4ef-4da7-b4a1-9ad1cfe1e95d"
        splunk-index: "main"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "true"
        splunk-format: "json"
        tag: "{{.Name}}/{{.ID}}"
    volumes:
      - .:/app

volumes:
  db_data: