global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "hostel-web"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["web:5000"]  # docker-compose service name

